"""
Memory Conflict Resolver
=========================

Arbitrates between conflicting goals generated by the GoalGenerator.
Implements a three-phase pipeline:

Phase 1: Severity-Gated Historical Dedup
    - Optimization goals: 7-day suppression
    - Maintenance/Risk goals: 24-48h suppression, only re-surface if metric worsened >10%
    - Safety/Critical goals: 0-day suppression (always nag)

Phase 2: Semantic Conflict Detection
    - Identifies contradictory goal pairs (opposing actions on shared equipment)
    - Tags conflicts with severity and evidence

Phase 3: Entropy-Aware Priority Adjustment
    - Reads entropy from ObservationStore (not physics engine)
    - Formula: Entropy ≈ ΔAlarms/Δt + Var(Metrics) + (1 - TrustMetric)
    - High entropy → boost safety, demote efficiency
"""

import logging
import uuid
import statistics
from enum import Enum
from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional, Tuple
from datetime import datetime, timedelta

logger = logging.getLogger("arvis.advisory.conflict_resolver")


# ============================================================================
# DATA MODELS
# ============================================================================

class ConflictType(str, Enum):
    """Types of goal conflicts."""
    OPPOSING_ACTION = "opposing_action"         # e.g., "reduce setpoint" vs "increase setpoint"
    RESOURCE_CONTENTION = "resource_contention"  # two goals competing for same equipment
    TEMPORAL_CLASH = "temporal_clash"             # conflicting deadlines
    SAFETY_EFFICIENCY_TRADEOFF = "safety_efficiency_tradeoff"  # save money vs prevent failure


class EntropyLevel(str, Enum):
    """Building operational entropy levels."""
    CALM = "calm"           # Normal operations, low volatility
    ELEVATED = "elevated"   # Some anomalies, moderate changes
    HIGH = "high"           # Multiple issues, rapid state changes
    CRITICAL = "critical"   # Crisis mode, safety-first


class SuppressionReason(str, Enum):
    """Why a goal was suppressed."""
    RECENTLY_REJECTED = "recently_rejected"
    METRIC_STABLE = "metric_stable"           # Re-surfaced maintenance but metric didn't worsen
    CONFLICT_RESOLVED = "conflict_resolved"   # Lost to a higher-priority conflicting goal


@dataclass
class MemoryConflict:
    """A detected conflict between two goals."""
    conflict_id: str
    goal_a_id: str
    goal_b_id: str
    conflict_type: ConflictType
    severity: str  # "critical", "high", "medium", "low"
    resolution: str  # Human-readable explanation of which goal wins and why
    winner_id: str
    loser_id: str
    memory_evidence: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "conflict_id": self.conflict_id,
            "goal_a_id": self.goal_a_id,
            "goal_b_id": self.goal_b_id,
            "conflict_type": self.conflict_type.value,
            "severity": self.severity,
            "resolution": self.resolution,
            "winner_id": self.winner_id,
            "loser_id": self.loser_id,
            "memory_evidence": self.memory_evidence
        }


@dataclass
class ConflictResolution:
    """Result of the full conflict resolution pipeline."""
    original_count: int
    resolved_goals: list  # List[ProactiveGoal] — filtered and re-scored
    suppressed_goals: list  # Goals removed by historical dedup
    conflicts: List[MemoryConflict]
    entropy_level: EntropyLevel
    entropy_score: float
    suppression_log: List[Dict[str, str]] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "original_count": self.original_count,
            "resolved_count": len(self.resolved_goals),
            "suppressed_count": len(self.suppressed_goals),
            "conflicts_detected": len(self.conflicts),
            "entropy_level": self.entropy_level.value,
            "entropy_score": round(self.entropy_score, 3),
            "suppression_log": self.suppression_log,
            "conflicts": [c.to_dict() for c in self.conflicts]
        }


# ============================================================================
# ENTROPY ESTIMATOR (Organic — reads from ObservationStore)
# ============================================================================

class EntropyEstimator:
    """
    Calculates building operational entropy from the ObservationStore.
    
    Uses the *observed* data rather than the physics engine's ground truth,
    giving the GoalGenerator an "organic" view that includes sensor noise,
    data latency, and LLM parsing artifacts.
    
    Formula:
        Entropy ≈ ΔAlarms/Δt + Var(key_metrics) + (1 - TrustMetric)
    """

    # Thresholds for entropy level classification
    CALM_THRESHOLD = 0.3
    ELEVATED_THRESHOLD = 0.6
    HIGH_THRESHOLD = 0.85

    def __init__(self, observation_store=None, recommendation_tracker=None):
        self.observations = observation_store
        self.tracker = recommendation_tracker

    def estimate(self, building_id: str, window_hours: int = 6) -> Tuple[EntropyLevel, float]:
        """
        Estimate the current entropy level for a building.
        
        Returns:
            Tuple of (EntropyLevel, raw_score)
        """
        alarm_rate = self._calculate_alarm_rate(window_hours)
        metric_variance = self._calculate_metric_variance(window_hours)
        trust_deficit = self._calculate_trust_deficit(building_id)

        # Composite entropy score (0.0 to ~1.5+, clamped to 1.0 for level mapping)
        raw_score = alarm_rate + metric_variance + trust_deficit

        # Classify
        if raw_score >= self.HIGH_THRESHOLD:
            level = EntropyLevel.CRITICAL
        elif raw_score >= self.ELEVATED_THRESHOLD:
            level = EntropyLevel.HIGH
        elif raw_score >= self.CALM_THRESHOLD:
            level = EntropyLevel.ELEVATED
        else:
            level = EntropyLevel.CALM

        logger.info(
            f"[ENTROPY] Building={building_id} | Score={raw_score:.3f} | Level={level.value} "
            f"(alarm_rate={alarm_rate:.3f}, variance={metric_variance:.3f}, trust_deficit={trust_deficit:.3f})"
        )

        return level, raw_score

    def _calculate_alarm_rate(self, window_hours: int) -> float:
        """ΔAlarms / Δt — rate of alarm observations in the window."""
        if not self.observations:
            return 0.0

        try:
            alarms = self.observations.get_recent(
                hours=window_hours, category="anomaly", limit=100
            )
            if not alarms:
                return 0.0

            # Normalize: >10 alarms/6h = max contribution (0.4)
            rate = len(alarms) / max(window_hours, 1)
            return min(0.4, rate / 10.0 * 0.4)

        except Exception as e:
            logger.warning(f"[ENTROPY] Alarm rate calculation failed: {e}")
            return 0.0

    def _calculate_metric_variance(self, window_hours: int) -> float:
        """Variance of key operational metrics from observations."""
        if not self.observations:
            return 0.0

        try:
            # Search for recent metric observations
            recent = self.observations.get_recent(hours=window_hours, limit=50)
            if not recent or len(recent) < 3:
                return 0.0

            # Extract importance scores as a proxy for "how unusual was this observation"
            importances = [obs.get("importance", 0.5) for obs in recent if isinstance(obs, dict)]
            if len(importances) < 3:
                return 0.0

            variance = statistics.variance(importances)
            # Normalize: high variance in importance = high entropy
            # Max contribution: 0.35
            return min(0.35, variance * 2.0)

        except Exception as e:
            logger.warning(f"[ENTROPY] Metric variance calculation failed: {e}")
            return 0.0

    def _calculate_trust_deficit(self, building_id: str) -> float:
        """(1 - TrustMetric) — how much trust has degraded."""
        if not self.tracker:
            return 0.0

        try:
            metrics = self.tracker.calculate_trust_metrics(
                window_days=7, building_id=building_id
            )
            if metrics is None:
                return 0.0

            # TrustMetrics has an adoption_rate field (0.0-1.0)
            trust = getattr(metrics, "adoption_rate", 0.9)
            # Max contribution: 0.25
            return min(0.25, (1.0 - trust) * 0.5)

        except Exception as e:
            logger.warning(f"[ENTROPY] Trust deficit calculation failed: {e}")
            return 0.0


# ============================================================================
# OPPOSING ACTION DETECTION
# ============================================================================

# Keywords that indicate opposing action vectors
_INCREASE_KEYWORDS = {"increase", "raise", "boost", "ramp up", "higher", "extend", "upgrade"}
_DECREASE_KEYWORDS = {"decrease", "reduce", "lower", "cut", "minimize", "limit", "downgrade"}
_SAFETY_KEYWORDS = {"safety", "prevent", "failure", "veto", "critical", "emergency", "alarm"}
_EFFICIENCY_KEYWORDS = {"save", "reduce cost", "optimize", "efficiency", "waste", "savings"}


def _extract_action_vector(suggested_actions: List[str]) -> str:
    """
    Determine whether a goal's actions lean toward 'increase' or 'decrease'.
    Returns 'increase', 'decrease', or 'neutral'.
    """
    if not suggested_actions:
        return "neutral"

    text = " ".join(suggested_actions).lower()

    increase_hits = sum(1 for kw in _INCREASE_KEYWORDS if kw in text)
    decrease_hits = sum(1 for kw in _DECREASE_KEYWORDS if kw in text)

    if increase_hits > decrease_hits:
        return "increase"
    elif decrease_hits > increase_hits:
        return "decrease"
    return "neutral"


def _is_safety_goal(goal) -> bool:
    """Check if a goal is safety-critical."""
    text = f"{goal.title} {goal.description}".lower()
    return goal.priority == "critical" or any(kw in text for kw in _SAFETY_KEYWORDS)


def _is_efficiency_goal(goal) -> bool:
    """Check if a goal is efficiency/cost-focused."""
    text = f"{goal.title} {goal.description}".lower()
    return goal.goal_type == "efficiency" or any(kw in text for kw in _EFFICIENCY_KEYWORDS)


# ============================================================================
# MEMORY CONFLICT RESOLVER
# ============================================================================

class MemoryConflictResolver:
    """
    Three-phase conflict arbitration for the GoalGenerator.
    
    Sits between the raw goal pipelines and the final output,
    ensuring that the system's accumulated operational memory
    informs goal prioritization — especially during high-entropy crises.
    """

    # Severity-Gated Dedup windows (in hours)
    OPTIMIZATION_SUPPRESSION_HOURS = 7 * 24   # 7 days
    MAINTENANCE_SUPPRESSION_HOURS = 48         # 48 hours
    MAINTENANCE_WORSENING_THRESHOLD = 0.10     # 10% metric worsening to re-surface
    # Safety/Critical: 0 suppression (always nag)

    def __init__(
        self,
        recommendation_tracker=None,
        observation_store=None,
        world_model=None
    ):
        self.tracker = recommendation_tracker
        self.observations = observation_store
        self.world_model = world_model
        self.entropy_estimator = EntropyEstimator(
            observation_store=observation_store,
            recommendation_tracker=recommendation_tracker
        )

    def resolve_conflicts(self, goals: list, building_id: str) -> ConflictResolution:
        """
        Run the full 3-phase conflict resolution pipeline.
        
        Args:
            goals: Raw list of ProactiveGoal objects from the three pipelines
            building_id: ID of the building being analyzed
            
        Returns:
            ConflictResolution with filtered goals, conflict annotations, and entropy info
        """
        original_count = len(goals)
        suppression_log = []

        logger.info(f"[CONFLICT_RESOLVER] Starting resolution for {original_count} goals")

        # ── Phase 1: Severity-Gated Historical Dedup ──
        active_goals, suppressed, phase1_log = self._phase1_historical_dedup(
            goals, building_id
        )
        suppression_log.extend(phase1_log)

        # ── Phase 2: Semantic Conflict Detection ──
        active_goals, conflicts = self._phase2_semantic_conflicts(active_goals)

        # ── Phase 3: Entropy-Aware Priority Adjustment ──
        entropy_level, entropy_score = self.entropy_estimator.estimate(building_id)
        active_goals = self._phase3_entropy_adjustment(active_goals, entropy_level, entropy_score)

        # Re-sort by adjusted score
        active_goals.sort(key=lambda g: g.score, reverse=True)

        logger.info(
            f"[CONFLICT_RESOLVER] Resolution complete: "
            f"{len(active_goals)}/{original_count} goals survived, "
            f"{len(suppressed)} suppressed, {len(conflicts)} conflicts detected, "
            f"entropy={entropy_level.value}"
        )

        return ConflictResolution(
            original_count=original_count,
            resolved_goals=active_goals,
            suppressed_goals=suppressed,
            conflicts=conflicts,
            entropy_level=entropy_level,
            entropy_score=entropy_score,
            suppression_log=suppression_log
        )

    # ────────────────────────────────────────────────────────────────────
    # PHASE 1: Severity-Gated Historical Dedup
    # ────────────────────────────────────────────────────────────────────

    def _phase1_historical_dedup(
        self, goals: list, building_id: str
    ) -> Tuple[list, list, List[Dict]]:
        """
        Check each goal against recommendation history.
        
        Suppression rules (Binary Escalation):
        - Optimization/Efficiency: 7-day window
        - Maintenance/Risk: 48h window, re-surface only if metric worsened >10%
        - Safety/Critical: NEVER suppress (0-day)
        """
        if not self.tracker:
            return goals, [], []

        active = []
        suppressed = []
        log = []

        try:
            recent_recs = self.tracker.get_recent_recommendations(
                window_days=7, building_id=building_id
            )
        except Exception as e:
            logger.warning(f"[PHASE1] Failed to fetch history: {e}")
            return goals, [], []

        # Build signature → recommendation map for fast lookup
        rec_signatures = {}
        for rec in recent_recs:
            if isinstance(rec, dict):
                sig = self._make_signature(rec)
                rec_signatures[sig] = rec
            elif hasattr(rec, "to_dict"):
                rec_dict = rec.to_dict() if callable(getattr(rec, "to_dict", None)) else {}
                sig = self._make_signature(rec_dict)
                rec_signatures[sig] = rec_dict

        for goal in goals:
            goal_sig = f"{goal.goal_type}:{goal.title}:{','.join(sorted(goal.equipment_ids))}"

            # Check if this goal was recently recommended
            matching_rec = rec_signatures.get(goal_sig)
            if not matching_rec:
                active.append(goal)
                continue

            # Determine suppression based on goal type (Binary Escalation)
            if _is_safety_goal(goal):
                # Safety/Critical: NEVER suppress
                active.append(goal)
                log.append({
                    "goal_id": goal.goal_id,
                    "action": "BYPASS_HISTORY",
                    "reason": "Safety/Critical goal — 0-day suppression policy"
                })
                continue

            rec_status = matching_rec.get("status", "unknown")
            was_rejected = rec_status in ("rejected", "dismissed", "ignored")

            if not was_rejected:
                # Accepted or pending — keep the goal
                active.append(goal)
                continue

            # ─── The goal was previously rejected ───

            rec_timestamp = matching_rec.get("created_at") or matching_rec.get("timestamp")
            if isinstance(rec_timestamp, str):
                try:
                    rec_time = datetime.fromisoformat(rec_timestamp)
                except (ValueError, TypeError):
                    rec_time = datetime.now() - timedelta(days=1)
            elif isinstance(rec_timestamp, datetime):
                rec_time = rec_timestamp
            else:
                rec_time = datetime.now() - timedelta(days=1)

            hours_since = (datetime.now() - rec_time).total_seconds() / 3600

            if goal.goal_type in ("efficiency", "optimization", "compliance"):
                # Optimization goals: 7-day suppression
                if hours_since < self.OPTIMIZATION_SUPPRESSION_HOURS:
                    suppressed.append(goal)
                    log.append({
                        "goal_id": goal.goal_id,
                        "action": "SUPPRESSED_BY_HISTORY",
                        "reason": f"Optimization goal rejected {hours_since:.0f}h ago (window: {self.OPTIMIZATION_SUPPRESSION_HOURS}h)"
                    })
                    continue

            elif goal.goal_type == "risk_mitigation":
                # Maintenance/Risk: 48h, re-surface only if metric worsened >10%
                if hours_since < self.MAINTENANCE_SUPPRESSION_HOURS:
                    metric_worsened = self._check_metric_worsening(goal, building_id)
                    if not metric_worsened:
                        suppressed.append(goal)
                        log.append({
                            "goal_id": goal.goal_id,
                            "action": "SUPPRESSED_BY_HISTORY",
                            "reason": f"Maintenance goal rejected {hours_since:.0f}h ago, metric stable (window: {self.MAINTENANCE_SUPPRESSION_HOURS}h)"
                        })
                        continue
                    else:
                        log.append({
                            "goal_id": goal.goal_id,
                            "action": "RESURFACED",
                            "reason": f"Maintenance goal rejected {hours_since:.0f}h ago but metric worsened >10%"
                        })

            # Passed all suppression gates
            active.append(goal)

        return active, suppressed, log

    def _make_signature(self, rec: Dict) -> str:
        """Create a dedup signature from a recommendation dict."""
        goal_type = rec.get("goal_type", rec.get("trigger_type", ""))
        title = rec.get("title", rec.get("context", {}).get("title", ""))
        eq_ids = rec.get("equipment_ids", [])
        if isinstance(eq_ids, list):
            eq_str = ",".join(sorted(eq_ids))
        else:
            eq_str = str(eq_ids)
        return f"{goal_type}:{title}:{eq_str}"

    def _check_metric_worsening(self, goal, building_id: str) -> bool:
        """
        Check if the underlying metric for a maintenance goal has worsened >10%.
        Uses the ObservationStore for organic readings.
        """
        if not self.observations:
            return True  # If we can't check, err on the side of re-surfacing

        try:
            # Search for observations related to this goal's equipment
            eq_query = " ".join(goal.equipment_ids) if goal.equipment_ids else goal.title
            recent_obs = self.observations.search(query=eq_query, limit=10)

            if not recent_obs or len(recent_obs) < 2:
                return True  # Not enough data — re-surface to be safe

            # Compare first vs last importance (proxy for metric severity)
            importances = [obs.get("importance", 0.5) for obs in recent_obs if isinstance(obs, dict)]
            if len(importances) >= 2:
                oldest = importances[-1]
                newest = importances[0]
                if oldest > 0:
                    change = (newest - oldest) / oldest
                    return change > self.MAINTENANCE_WORSENING_THRESHOLD

            return True  # Default: re-surface

        except Exception as e:
            logger.warning(f"[PHASE1] Metric worsening check failed: {e}")
            return True

    # ────────────────────────────────────────────────────────────────────
    # PHASE 2: Semantic Conflict Detection
    # ────────────────────────────────────────────────────────────────────

    def _phase2_semantic_conflicts(self, goals: list) -> Tuple[list, List[MemoryConflict]]:
        """
        Detect pairs of goals that semantically conflict.
        
        Conflict conditions:
        1. Shared equipment IDs + opposing action vectors
        2. Safety vs efficiency tradeoff
        3. Resource contention (same equipment, different goals)
        
        Resolution: Higher-scoring goal wins. Safety always beats efficiency.
        """
        conflicts = []
        losers = set()  # goal_ids that lost a conflict

        for i, goal_a in enumerate(goals):
            for j, goal_b in enumerate(goals):
                if j <= i:
                    continue

                # Check for conflicts
                conflict = self._detect_conflict(goal_a, goal_b)
                if conflict:
                    conflicts.append(conflict)
                    losers.add(conflict.loser_id)

        # Remove losers but keep them accessible via the conflict log
        active = [g for g in goals if g.goal_id not in losers]

        if conflicts:
            logger.info(
                f"[PHASE2] Detected {len(conflicts)} conflicts, "
                f"removed {len(losers)} losing goals"
            )

        return active, conflicts

    def _detect_conflict(self, goal_a, goal_b) -> Optional[MemoryConflict]:
        """Detect if two goals conflict. Returns MemoryConflict or None."""

        # 1. Check for shared equipment
        shared_equipment = set(goal_a.equipment_ids) & set(goal_b.equipment_ids)

        # 2. Determine action vectors
        vector_a = _extract_action_vector(goal_a.suggested_actions)
        vector_b = _extract_action_vector(goal_b.suggested_actions)

        # 3. Safety vs Efficiency tradeoff
        a_safety = _is_safety_goal(goal_a)
        b_safety = _is_safety_goal(goal_b)
        a_efficiency = _is_efficiency_goal(goal_a)
        b_efficiency = _is_efficiency_goal(goal_b)

        conflict_type = None
        severity = "medium"

        if (a_safety and b_efficiency) or (b_safety and a_efficiency):
            conflict_type = ConflictType.SAFETY_EFFICIENCY_TRADEOFF
            severity = "critical"
        elif shared_equipment and vector_a != "neutral" and vector_b != "neutral" and vector_a != vector_b:
            conflict_type = ConflictType.OPPOSING_ACTION
            severity = "high"
        elif shared_equipment and goal_a.goal_type != goal_b.goal_type:
            conflict_type = ConflictType.RESOURCE_CONTENTION
            severity = "medium"

        if not conflict_type:
            return None

        # Resolve: Safety always wins. Otherwise, higher score wins.
        if a_safety and not b_safety:
            winner, loser = goal_a, goal_b
        elif b_safety and not a_safety:
            winner, loser = goal_b, goal_a
        elif goal_a.score >= goal_b.score:
            winner, loser = goal_a, goal_b
        else:
            winner, loser = goal_b, goal_a

        evidence = []
        if shared_equipment:
            evidence.append(f"Shared equipment: {shared_equipment}")
        if vector_a != vector_b:
            evidence.append(f"Opposing actions: {goal_a.title}={vector_a}, {goal_b.title}={vector_b}")

        return MemoryConflict(
            conflict_id=str(uuid.uuid4()),
            goal_a_id=goal_a.goal_id,
            goal_b_id=goal_b.goal_id,
            conflict_type=conflict_type,
            severity=severity,
            resolution=f"'{winner.title}' wins over '{loser.title}' ({conflict_type.value})",
            winner_id=winner.goal_id,
            loser_id=loser.goal_id,
            memory_evidence=evidence
        )

    # ────────────────────────────────────────────────────────────────────
    # PHASE 3: Entropy-Aware Priority Adjustment
    # ────────────────────────────────────────────────────────────────────

    def _phase3_entropy_adjustment(
        self, goals: list, entropy_level: EntropyLevel, entropy_score: float
    ) -> list:
        """
        Adjust goal scores based on current building entropy.
        
        High entropy → boost safety/risk goals, demote efficiency/optimization.
        This ensures that during a heatwave crisis, "save money" goals
        are automatically killed in favor of "save the building."
        """
        if entropy_level == EntropyLevel.CALM:
            return goals  # No adjustment needed in calm conditions

        # Adjustment multipliers by entropy level
        multipliers = {
            EntropyLevel.ELEVATED: {"safety_boost": 1.15, "efficiency_penalty": 0.90},
            EntropyLevel.HIGH:     {"safety_boost": 1.35, "efficiency_penalty": 0.60},
            EntropyLevel.CRITICAL: {"safety_boost": 1.50, "efficiency_penalty": 0.30},
        }

        m = multipliers.get(entropy_level, {"safety_boost": 1.0, "efficiency_penalty": 1.0})

        for goal in goals:
            original_score = goal.score

            if _is_safety_goal(goal) or goal.goal_type == "risk_mitigation":
                goal.score = min(1.0, goal.score * m["safety_boost"])
                if goal.score != original_score:
                    logger.debug(
                        f"[PHASE3] Boosted safety goal '{goal.title}': "
                        f"{original_score:.2f} → {goal.score:.2f}"
                    )

            elif _is_efficiency_goal(goal) or goal.goal_type in ("efficiency", "optimization"):
                goal.score = goal.score * m["efficiency_penalty"]
                if goal.score != original_score:
                    logger.debug(
                        f"[PHASE3] Demoted efficiency goal '{goal.title}': "
                        f"{original_score:.2f} → {goal.score:.2f}"
                    )

                # In CRITICAL entropy, also downgrade priority label
                if entropy_level == EntropyLevel.CRITICAL:
                    if goal.priority in ("critical", "high"):
                        goal.priority = "medium"
                    elif goal.priority == "medium":
                        goal.priority = "low"

        logger.info(
            f"[PHASE3] Applied {entropy_level.value} entropy adjustments "
            f"(safety_boost={m['safety_boost']}, efficiency_penalty={m['efficiency_penalty']})"
        )

        return goals
