"""
Advisory Tool Definitions
=========================

Tools for proactive advisory, briefings, and feedback.
"""

ADVISORY_TOOLS = [
    {
        "name": "get_advisory_recommendations",
        "description": "Get AI-generated, ML-ranked recommendations for resolving operational issues. Use this when an alarm is detected or an optimization opportunity is found. Returns multiple options ranked by predicted operator preference, including cost, risk, and benefit analysis.",
        "parameters": {
            "type": "object",
            "properties": {
                "context": {
                    "type": "string",
                    "description": "Context for recommendations (e.g., 'high energy consumption in zone A')"
                },
                "equipment_id": {
                    "type": "string",
                    "description": "Related equipment (optional)"
                },
                "alarm_id": {
                    "type": "string",
                    "description": "Related alarm (optional)"
                },
                "top_k": {
                    "type": "integer",
                    "description": "Number of recommendations to return (default: 3)",
                    "default": 3
                }
            },
            "required": ["context"]
        }
    },
    {
        "name": "check_goals",
        "description": "Check for active proactive goals generated by the autonomous goal generator. Returns prioritized list of risks, waste reduction opportunities, and fleet optimization targets.",
        "parameters": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "description": "Filter by category: risk, waste, fleet, comfort, compliance",
                    "enum": ["risk", "waste", "fleet", "comfort", "compliance"]
                }
            },
            "required": []
        }
    },
    {
        "name": "generate_briefing",
        "description": "Generate a proactive operations briefing. Instead of the user hunting for issues, this provides: critical items needing attention, overnight anomalies, optimization wins, today's context (weather, events, tariffs), and prioritized recommendations.",
        "parameters": {
            "type": "object",
            "properties": {
                "briefing_type": {
                    "type": "string",
                    "description": "Type of briefing: daily_morning, shift_handoff, urgent_risk, end_of_day",
                    "enum": ["daily_morning", "shift_handoff", "urgent_risk", "end_of_day"],
                    "default": "daily_morning"
                },
                "focus_area": {
                    "type": "string",
                    "description": "Optional focus area (e.g., 'energy', 'comfort', 'maintenance')"
                }
            },
            "required": []
        }
    },
    {
        "name": "run_briefing",
        "description": "Generate an on-demand briefing (Daily Morning or Urgent Risk). Useful if the user asks 'What should I focus on today?' or 'Give me a briefing'.",
        "parameters": {
            "type": "object",
            "properties": {
                "briefing_type": {
                    "type": "string",
                    "description": "Type: daily_morning or urgent_risk",
                    "enum": ["daily_morning", "urgent_risk"],
                    "default": "daily_morning"
                }
            },
            "required": []
        }
    },
    {
        "name": "submit_feedback",
        "description": "Submit operator feedback for active learning. Use when the user corrects the system, explains a decision, or answers a specific question from the agent.",
        "parameters": {
            "type": "object",
            "properties": {
                "feedback_type": {
                    "type": "string",
                    "description": "Type: correction, explanation, preference, rating",
                    "enum": ["correction", "explanation", "preference", "rating"]
                },
                "target": {
                    "type": "string",
                    "description": "What the feedback is about (recommendation_id, action, etc.)"
                },
                "content": {
                    "type": "string",
                    "description": "The feedback content"
                },
                "rating": {
                    "type": "integer",
                    "description": "Optional rating 1-5 (for rating type)",
                    "minimum": 1,
                    "maximum": 5
                }
            },
            "required": ["feedback_type", "target", "content"]
        }
    },
    {
        "name": "get_trust_metrics",
        "description": "Get current advisor reliability metrics and system trust scores. Shows adoption rates, accuracy, and any detected model drift.",
        "parameters": {
            "type": "object",
            "properties": {},
            "required": []
        }
    },
]
