"""
ARVIS Tool Executor
-------------------
Executes tool calls generated by the LLM agent.
Enhanced with think, log_memory, and mission tool handlers.
"""

import logging
from typing import Dict, Any, List, Optional

from agent.tools.handlers.think_handler import ThinkToolHandler

logger = logging.getLogger("arvis.executor")


class ToolExecutor:
    """
    Executes tool calls from LLM.
    Routes calls to appropriate handlers based on tool name.
    """
    
    def __init__(self, device, state_engine, automations, event_bus,
                 learning_engine=None, mission_manager=None):
        self.device = device
        self.state_engine = state_engine
        self.automations = automations
        self.event_bus = event_bus
        self.learning_engine = learning_engine
        self.mission_manager = mission_manager
        
        # Initialize tool handlers
        self.think_handler = ThinkToolHandler()
        
        # Subscribe to tool calls generated by LLM
        self.event_bus.subscribe("tool_calls_generated", self.on_tool_calls)
        
        print("[ToolExecutor] Initialized with enhanced tool handlers")

    def on_tool_calls(self, event: Dict[str, Any]) -> None:
        """Handle tool_calls_generated event"""
        tool_calls = event.get("payload", [])
        self.execute(tool_calls)

    def execute(self, tool_calls: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Execute a list of tool calls.
        
        Args:
            tool_calls: List of tool call dicts with 'tool' and 'args' keys
            
        Returns:
            List of result dicts with status and any output
        """
        print(f"[ToolExecutor] Executing {len(tool_calls)} tool calls")
        results = []
        
        for call in tool_calls:
            # Support both 'tool' and 'tool_name' keys for compatibility
            name = call.get("tool") or call.get("tool_name")
            args = call.get("args") or call.get("arguments", {})
            
            if not name:
                print(f"[ToolExecutor] Warning: Missing tool name in call: {call}")
                results.append({"status": "error", "message": "Missing tool name"})
                continue
                
            print(f"[ToolExecutor] -> {name}({args})")

            try:
                result = self._execute_single(name, args)
                results.append(result)
            except Exception as e:
                print(f"[ToolExecutor] Error executing {name}: {e}")
                logger.error(f"Tool execution error: {name} - {e}")
                results.append({"status": "error", "tool": name, "message": str(e)})
        
        return results

    def _execute_single(self, name: str, args: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute a single tool call.
        
        Args:
            name: Tool name
            args: Tool arguments
            
        Returns:
            Result dict with status
        """
        # ═══════════════════════════════════════════════════════════
        # REASONING TOOLS
        # ═══════════════════════════════════════════════════════════
        
        if name == "think":
            result = self.think_handler.execute(args.get("reasoning", ""))
            return {"status": "success" if result.get("success") else "error", "tool": name, **result}
        
        # ═══════════════════════════════════════════════════════════
        # DEVICE CONTROL TOOLS
        # ═══════════════════════════════════════════════════════════
        
        elif name == "turn_on":
            device_id = args["device_id"]
            endpoint = args["endpoint"]
            brightness = args.get("brightness")
            color_temp = args.get("color_temp")
            
            # Execute core action
            self.device.turn_on(device_id, endpoint)
            
            # Stub brightness/color_temp (TODO: implement when hardware supports)
            if brightness is not None:
                logger.info(f"Brightness {brightness}% requested for {device_id} (TODO: implement)")
                print(f"[ToolExecutor] Brightness {brightness}% (not yet implemented)")
            if color_temp is not None:
                logger.info(f"Color temp {color_temp}K requested for {device_id} (TODO: implement)")
                print(f"[ToolExecutor] Color temp {color_temp}K (not yet implemented)")
            
            self.event_bus.publish({
                "type": "relay_toggled",
                "payload": {"device": device_id, "endpoint": endpoint, "state": "on"}
            })
            return {"status": "success", "tool": name}

        elif name == "turn_off":
            self.device.turn_off(args["device_id"], args["endpoint"])
            self.event_bus.publish({
                "type": "relay_toggled",
                "payload": {"device": args["device_id"], "endpoint": args["endpoint"], "state": "off"}
            })
            return {"status": "success", "tool": name}

        # ═══════════════════════════════════════════════════════════
        # ROUTINE TOOLS
        # ═══════════════════════════════════════════════════════════

        elif name == "create_routine":
            self.automations.create(args["name"], args["trigger"], args["actions"])
            return {"status": "success", "tool": name}
                
        elif name == "run_routine":
            routine_name = args.get("routine_name") or args.get("name")
            actions = self.automations.run(routine_name)
            # Recursively execute actions from routine
            self.execute(actions)
            return {"status": "success", "tool": name}

        # ═══════════════════════════════════════════════════════════
        # USER INTERACTION TOOLS
        # ═══════════════════════════════════════════════════════════
                
        elif name == "ask_user":
            question = args.get("question") or args.get("message")
            options = args.get("options", [])
            print(f"🤖 ARVIS ASKS: {question}")
            if options:
                print(f"   Options: {', '.join(options)}")
            # In a real app, this would push to UI/TTS
            self.event_bus.publish({
                "type": "user_query",
                "payload": {"question": question, "options": options}
            })
            return {"status": "success", "tool": name}

        # ═══════════════════════════════════════════════════════════
        # MEMORY & LOGGING TOOLS
        # ═══════════════════════════════════════════════════════════
                
        elif name == "log_note":
            note = args.get("note") or args.get("text")
            category = args.get("category", "general")
            print(f"📝 NOTE [{category}]: {note}")
            logger.info(f"Note [{category}]: {note}")
            return {"status": "success", "tool": name}
        
        elif name == "log_memory":
            title = args.get("title")
            knowledge = args.get("knowledge")
            action = args.get("action", "create")
            existing_id = args.get("existing_id")
            
            if self.learning_engine:
                try:
                    if action == "create":
                        self.learning_engine.store_memory(title, knowledge)
                    elif action == "update" and existing_id:
                        self.learning_engine.update_memory(existing_id, knowledge)
                    elif action == "delete" and existing_id:
                        self.learning_engine.delete_memory(existing_id)
                    print(f"🧠 MEMORY [{action}]: {title}")
                    return {"status": "success", "tool": name}
                except Exception as e:
                    logger.error(f"Memory operation failed: {e}")
                    return {"status": "error", "tool": name, "message": str(e)}
            else:
                print(f"[ToolExecutor] log_memory called but no LearningEngine configured")
                return {"status": "error", "tool": name, "message": "LearningEngine not configured"}

        # ═══════════════════════════════════════════════════════════
        # MISSION TOOLS
        # ═══════════════════════════════════════════════════════════
        
        elif name == "create_mission":
            if self.mission_manager:
                mission_name = args.get("name")
                description = args.get("description", "")
                layers = args.get("layers", [])
                
                try:
                    mission_id = self.mission_manager.create_mission(
                        mission_type=mission_name,
                        context={"description": description, "layers": layers}
                    )
                    print(f"🚀 MISSION CREATED: {mission_name} (ID: {mission_id})")
                    return {"status": "success", "tool": name, "mission_id": mission_id}
                except Exception as e:
                    logger.error(f"Mission creation failed: {e}")
                    return {"status": "error", "tool": name, "message": str(e)}
            else:
                return {"status": "error", "tool": name, "message": "MissionManager not configured"}
        
        elif name == "update_mission_status":
            if self.mission_manager:
                mission_id = args.get("mission_id")
                step_id = args.get("step_id")
                status = args.get("status")
                
                try:
                    self.mission_manager.update_step_status(mission_id, step_id, status)
                    print(f"📋 MISSION UPDATE: {mission_id}/{step_id} -> {status}")
                    return {"status": "success", "tool": name}
                except Exception as e:
                    logger.error(f"Mission status update failed: {e}")
                    return {"status": "error", "tool": name, "message": str(e)}
            else:
                return {"status": "error", "tool": name, "message": "MissionManager not configured"}

        # ═══════════════════════════════════════════════════════════
        # SECURITY TOOLS
        # ═══════════════════════════════════════════════════════════
        
        elif name == "request_pin_verification":
            operation = args.get("operation", "unknown operation")
            reason = args.get("reason", "security verification required")
            
            # Get security manager
            try:
                from agent.security.security_manager import get_security_manager
                security = get_security_manager()
                
                if not security.is_pin_configured():
                    message = "🔐 Security PIN not configured. Please set up a PIN first by saying: 'Set my security PIN to XXXX'"
                else:
                    message = f"🔐 This operation requires PIN verification.\nOperation: {operation}\nReason: {reason}\nPlease enter your security PIN to proceed."
                
                print(f"🔐 PIN VERIFICATION REQUESTED: {operation}")
                
                # Publish to user
                self.event_bus.publish({
                    "type": "user_query",
                    "source": "security_manager",
                    "payload": {"question": message, "requires_pin": True, "operation": operation}
                })
                
                return {"status": "success", "tool": name, "awaiting_pin": True, "operation": operation}
            except Exception as e:
                logger.error(f"Security verification request failed: {e}")
                return {"status": "error", "tool": name, "message": str(e)}
        
        elif name == "verify_pin":
            pin = args.get("pin", "")
            
            try:
                from agent.security.security_manager import get_security_manager
                security = get_security_manager()
                
                result = security.verify_pin(pin)
                
                if result["success"]:
                    print(f"✅ PIN VERIFIED - Session active")
                    self.event_bus.publish({
                        "type": "security_verified",
                        "source": "security_manager",
                        "payload": {"verified": True}
                    })
                else:
                    print(f"❌ PIN VERIFICATION FAILED: {result.get('error', 'Unknown error')}")
                    self.event_bus.publish({
                        "type": "user_query",
                        "source": "security_manager",
                        "payload": {"question": f"❌ {result.get('error', 'Verification failed')}", "type": "security_error"}
                    })
                
                return {"status": "success" if result["success"] else "error", "tool": name, **result}
            except Exception as e:
                logger.error(f"PIN verification failed: {e}")
                return {"status": "error", "tool": name, "message": str(e)}
        
        elif name == "setup_security_pin":
            new_pin = args.get("new_pin", "")
            
            try:
                from agent.security.security_manager import get_security_manager
                security = get_security_manager()
                
                result = security.setup_pin(new_pin)
                
                if result["success"]:
                    print(f"✅ SECURITY PIN CONFIGURED")
                    self.event_bus.publish({
                        "type": "user_query",
                        "source": "security_manager",
                        "payload": {"question": "✅ Security PIN has been configured successfully!", "type": "security_success"}
                    })
                else:
                    print(f"❌ PIN SETUP FAILED: {result.get('error', 'Unknown error')}")
                
                return {"status": "success" if result["success"] else "error", "tool": name, **result}
            except Exception as e:
                logger.error(f"PIN setup failed: {e}")
                return {"status": "error", "tool": name, "message": str(e)}

        # ═══════════════════════════════════════════════════════════
        # UNKNOWN TOOL
        # ═══════════════════════════════════════════════════════════
        
        else:
            print(f"[ToolExecutor] Unknown tool: {name}")
            return {"status": "error", "tool": name, "message": f"Unknown tool: {name}"}

