class ToolExecutor:
    def __init__(self, device, state_engine, automations, event_bus):
        self.device = device
        self.state_engine = state_engine
        self.automations = automations
        self.event_bus = event_bus
        
        # Subscribe to tool calls generated by LLM
        self.event_bus.subscribe("tool_calls_generated", self.on_tool_calls)

    def on_tool_calls(self, event):
        tool_calls = event.get("payload", [])
        self.execute(tool_calls)

    def execute(self, tool_calls):
        print(f"[ToolExecutor] Executing {len(tool_calls)} tool calls")
        results = []
        for call in tool_calls:
            # Support both 'tool' and 'tool_name' keys for compatibility
            name = call.get("tool") or call.get("tool_name")
            args = call.get("args") or call.get("arguments", {})
            
            if not name:
                print(f"[ToolExecutor] Warning: Missing tool name in call: {call}")
                results.append({"status": "error", "message": "Missing tool name"})
                continue
                
            print(f"[ToolExecutor] -> {name}({args})")

            try:
                if name == "turn_on":
                    self.device.turn_on(args["device_id"], args["endpoint"])
                    self.event_bus.publish({
                        "type": "relay_toggled",
                        "payload": {"device": args["device_id"], "endpoint": args["endpoint"], "state": "on"}
                    })
                    results.append({"status": "success", "tool": name})
    
                elif name == "turn_off":
                    self.device.turn_off(args["device_id"], args["endpoint"])
                    self.event_bus.publish({
                        "type": "relay_toggled",
                        "payload": {"device": args["device_id"], "endpoint": args["endpoint"], "state": "off"}
                    })
                    results.append({"status": "success", "tool": name})

                elif name == "create_routine":
                    self.automations.create(args["name"], args["trigger"], args["actions"])
                    results.append({"status": "success", "tool": name})
                        
                elif name == "run_routine":
                    actions = self.automations.run(args["name"])
                    # Recursively execute actions from routine
                    # We need to format them as tool calls
                    self.execute(actions)
                    results.append({"status": "success", "tool": name})
                        
                elif name == "ask_user":
                    print(f"AGENCY REQUEST: {args['message']}")
                    # In a real app, this would push to UI
                    results.append({"status": "success", "tool": name})
                        
                elif name == "log_note":
                    print(f"NOTE: {args['text']}")
                    results.append({"status": "success", "tool": name})

                else:
                    print(f"[ToolExecutor] Unknown tool: {name}")
                    results.append({"status": "error", "message": f"Unknown tool: {name}"})
            except Exception as e:
                print(f"[ToolExecutor] Error executing {name}: {e}")
                results.append({"status": "error", "message": str(e)})
        
        return results
