"""
Agentic Option Generator
=========================

LLM-powered option generation through agentic reasoning.
NOT rule-based - uses RAG + reasoning to generate novel options.

The LLM:
1. Analyzes current context
2. Retrieves similar historical scenarios
3. Reasons about cause-effect chains
4. Generates 5 distinct options with rationale
"""

import json
import logging
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime

logger = logging.getLogger("arvis.advisory.agentic.generator")


@dataclass
class GeneratedOption:
    """An option generated by the agentic system"""
    action_type: str
    action_description: str
    equipment_id: str
    
    # Impacts (estimated by LLM reasoning)
    estimated_cost_qar: float = 0.0
    estimated_time_min: int = 30
    risk_score: int = 3  # 1-5
    comfort_score: int = 3  # 1-5
    energy_impact_pct: float = 0.0  # Negative = saves energy
    gsas_impact: float = 0.0
    
    # Reasoning
    mechanism: str = ""  # Why this might work
    risks: str = ""  # What could go wrong
    historical_precedent: str = ""  # Similar past cases
    
    # Metadata
    requires_shutdown: bool = False
    requires_operator_presence: bool = True
    is_reversible: bool = True
    intensity: float = 0.5  # 0-1
    
    # ═══════════════════════════════════════════════════════════════════════
    # NEW: Graph metadata for traceability (3.2 enhancement)
    # ═══════════════════════════════════════════════════════════════════════
    affected_nodes: List[str] = field(default_factory=list)
    """List of equipment IDs affected by this action"""
    
    traversal_path: List[str] = field(default_factory=list)
    """Order of equipment affected (source → ... → destination)"""
    
    required_state_changes: Dict[str, Any] = field(default_factory=dict)
    """What state changes are needed {equipment_id: {param: value}}"""
    
    safety_constraints: List[str] = field(default_factory=list)
    """What must be checked before executing"""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "action_type": self.action_type,
            "action": self.action_type,  # Alias
            "action_description": self.action_description,
            "equipment_id": self.equipment_id,
            "estimated_cost_qar": self.estimated_cost_qar,
            "estimated_time_min": self.estimated_time_min,
            "risk_score": self.risk_score,
            "comfort_score": self.comfort_score,
            "energy_impact_pct": self.energy_impact_pct,
            "gsas_impact": self.gsas_impact,
            "mechanism": self.mechanism,
            "risks": self.risks,
            "historical_precedent": self.historical_precedent,
            "requires_shutdown": self.requires_shutdown,
            "requires_operator_presence": self.requires_operator_presence,
            "is_reversible": self.is_reversible,
            "intensity": self.intensity,
            # Graph metadata
            "affected_nodes": self.affected_nodes,
            "traversal_path": self.traversal_path,
            "required_state_changes": self.required_state_changes,
            "safety_constraints": self.safety_constraints,
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "GeneratedOption":
        return cls(
            action_type=data.get("action_type", data.get("action", "unknown")),
            action_description=data.get("action_description", ""),
            equipment_id=data.get("equipment_id", ""),
            estimated_cost_qar=data.get("estimated_cost_qar", 0),
            estimated_time_min=data.get("estimated_time_min", 30),
            risk_score=data.get("risk_score", 3),
            comfort_score=data.get("comfort_score", 3),
            energy_impact_pct=data.get("energy_impact_pct", 0),
            gsas_impact=data.get("gsas_impact", 0),
            mechanism=data.get("mechanism", ""),
            risks=data.get("risks", ""),
            historical_precedent=data.get("historical_precedent", ""),
            requires_shutdown=data.get("requires_shutdown", False),
            requires_operator_presence=data.get("requires_operator_presence", True),
            is_reversible=data.get("is_reversible", True),
            intensity=data.get("intensity", 0.5),
            # Graph metadata
            affected_nodes=data.get("affected_nodes", []),
            traversal_path=data.get("traversal_path", []),
            required_state_changes=data.get("required_state_changes", {}),
            safety_constraints=data.get("safety_constraints", []),
        )


@dataclass
class HistoricalScenario:
    """A past scenario for RAG context"""
    scenario_id: str
    context_summary: str
    issue_type: str
    operator_action: str
    outcome_quality: str
    time_to_resolution_min: int
    cost_qar: float
    similarity_score: float = 0.0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "scenario_id": self.scenario_id,
            "context": self.context_summary,
            "issue": self.issue_type,
            "action_taken": self.operator_action,
            "outcome": self.outcome_quality,
            "resolution_time": f"{self.time_to_resolution_min} min",
            "cost": f"{self.cost_qar} QAR",
        }


class AgenticOptionGenerator:
    """
    LLM-powered option generator with RAG grounding.
    
    Uses retrieval-augmented generation to:
    1. Find similar historical scenarios
    2. Ground options in past experience
    3. Generate novel, context-specific options
    4. Explain reasoning for each option
    """
    
    SYSTEM_PROMPT = '''You are ARVIS, an expert building operations AI advisor for Qatar/GCC.

Your role is to generate 5 DISTINCT action options for operational issues.
You must reason about each situation specifically - do NOT use generic templates.

## Qatar Context
- Electricity: KAHRAMAA rates (commercial: 0.16-0.23 QAR/kWh)
- Climate: Extreme summer heat (45°C+), sandstorms, high humidity
- Schedule: Work week Sun-Thu, weekends Fri-Sat
- Standards: GSAS sustainability certification
- Cultural: Ramadan schedule shifts, prayer times

## For Each Option, Provide:
1. action_type: Short identifier (e.g., "reduce_load", "stage_down", "shutdown")
2. action_description: Detailed action steps
3. equipment_id: Which equipment to act on
4. estimated_cost_qar: Estimated cost in QAR
5. estimated_time_min: Time to implement
6. risk_score: 1-5 (1=minimal, 5=high risk)
7. comfort_score: 1-5 (1=poor comfort, 5=excellent)
8. energy_impact_pct: % change (negative=saves energy)
9. gsas_impact: Impact on GSAS score (-0.1 to +0.1)
10. mechanism: WHY this works (physics/engineering reasoning)
11. risks: What could go wrong
12. historical_precedent: Reference to similar past cases (if provided)
13. requires_shutdown: true/false
14. is_reversible: true/false
15. intensity: 0-1 (0=gentle, 1=aggressive)

## Graph Traceability (IMPORTANT)
For each option, also provide:
16. affected_nodes: List of ALL equipment IDs affected by this action
17. traversal_path: Order of equipment from source → destination (e.g., ["CHILLER-01", "AHU-01", "VAV-01-01"])
18. required_state_changes: What state changes needed: {equipment_id: {param: new_value}}
19. safety_constraints: What must be verified before executing

## Option Diversity
Generate options ranging from:
- Conservative (low risk, gradual)
- Moderate (balanced approach)
- Aggressive (fast action, higher risk)

## Output Format
Return ONLY valid JSON array of 5 options. No markdown, no explanation outside JSON.'''

    def __init__(self, llm=None, scenario_retriever=None, equipment_graph=None):
        """
        Initialize agentic option generator.
        
        Args:
            llm: UnifiedLLM instance (will create if not provided)
            scenario_retriever: ScenarioRetriever for RAG (optional)
            equipment_graph: EquipmentGraph for topology-aware generation (3.1/3.2 enhancement)
        """
        self.llm = llm
        self.scenario_retriever = scenario_retriever
        self.equipment_graph = equipment_graph
        
        # Import LLM if not provided
        if self.llm is None:
            try:
                from agent_unified.llm import UnifiedLLM
                self.llm = UnifiedLLM()
            except ImportError:
                logger.warning("UnifiedLLM not available")
        
        logger.info("AgenticOptionGenerator initialized (graph=%s)", equipment_graph is not None)
    
    async def generate_options(
        self,
        context: Dict[str, Any],
        issue_type: str,
        equipment_id: str,
        building_profile: Optional[Dict] = None,
        num_options: int = 5
    ) -> List[GeneratedOption]:
        """
        Generate options through LLM agentic reasoning.
        
        Args:
            context: Current operational context
            issue_type: Type of issue (e.g., "high_head_pressure")
            equipment_id: Equipment identifier
            building_profile: Optional building profile
            num_options: Number of options to generate
            
        Returns:
            List of GeneratedOption objects
        """
        # Retrieve similar historical scenarios (with graph filter if available)
        similar_scenarios = []
        if self.scenario_retriever:
            if self.equipment_graph and hasattr(self.scenario_retriever, 'retrieve_with_graph_filter'):
                # Use graph-filtered retrieval (3.1 enhancement)
                similar_scenarios = await self.scenario_retriever.retrieve_with_graph_filter(
                    context=context,
                    equipment_id=equipment_id,
                    issue_type=issue_type
                )
            else:
                similar_scenarios = await self._retrieve_scenarios(context, issue_type)
        
        # Get equipment topology context (3.2 enhancement)
        topology_context = None
        if self.equipment_graph:
            topology_context = self.equipment_graph.get_subgraph_for_context(equipment_id)
        
        # Build the prompt
        prompt = self._build_prompt(
            context, issue_type, equipment_id, 
            building_profile, similar_scenarios, num_options,
            topology_context=topology_context
        )
        
        # Call LLM
        try:
            options = await self._call_llm(prompt)
            
            # Validate options against graph topology if available
            if self.equipment_graph:
                options = self._validate_options_topology(options, equipment_id)
            
            return options
        except Exception as e:
            logger.error("LLM option generation failed: %s", e)
            # Return fallback options
            return self._generate_fallback_options(issue_type, equipment_id)
    
    def _build_prompt(
        self,
        context: Dict[str, Any],
        issue_type: str,
        equipment_id: str,
        building_profile: Optional[Dict],
        similar_scenarios: List[HistoricalScenario],
        num_options: int,
        topology_context: Optional[Dict] = None  # 3.2 enhancement
    ) -> str:
        """Build the LLM prompt with context"""
        parts = []
        
        # Current situation
        parts.append("## Current Situation")
        parts.append(f"Issue Type: {issue_type}")
        parts.append(f"Equipment: {equipment_id}")
        parts.append(f"Timestamp: {context.get('timestamp', datetime.now().isoformat())}")
        
        # Context details
        parts.append("\n## Current Readings")
        context_items = [
            f"- Outdoor Temp: {context.get('outdoor_temp_c', 'N/A')}°C",
            f"- Outdoor Humidity: {context.get('outdoor_humidity_pct', 'N/A')}%",
            f"- Zone Temp Avg: {context.get('zone_temp_avg_c', 'N/A')}°C",
            f"- Cooling Load: {context.get('cooling_load_pct', 'N/A')}%",
            f"- Occupancy: {context.get('occupancy_ratio', 'N/A')}",
        ]
        parts.extend(context_items)
        
        # Equipment topology (3.2 enhancement)
        if topology_context:
            parts.append("\n## Equipment Topology")
            parts.append(f"- Focus Equipment: {topology_context.get('focus_equipment')} ({topology_context.get('focus_type')})")
            if topology_context.get('upstream_chain'):
                parts.append(f"- Upstream Chain: {' → '.join(topology_context['upstream_chain'])} → {equipment_id}")
            if topology_context.get('downstream_children'):
                parts.append(f"- Downstream Equipment: {', '.join(topology_context['downstream_children'])}")
            parts.append(f"- Valid Equipment IDs: {', '.join(topology_context.get('neighborhood', []))}")
            parts.append("\nIMPORTANT: affected_nodes and traversal_path MUST only include IDs from the valid equipment list above.")
        
        # Building profile
        if building_profile:
            parts.append("\n## Building Profile")
            parts.append(f"- Type: {building_profile.get('type', 'commercial')}")
            parts.append(f"- GSAS Target: {building_profile.get('gsas_target', 'N/A')}")
            parts.append(f"- Cooling Capacity: {building_profile.get('cooling_capacity_tons', 'N/A')} tons")
        
        # Historical scenarios (RAG)
        if similar_scenarios:
            parts.append("\n## Similar Past Scenarios")
            for i, scenario in enumerate(similar_scenarios[:5], 1):
                parts.append(f"\n### Scenario {i} (similarity: {scenario.similarity_score:.2f})")
                parts.append(f"- Issue: {scenario.issue_type}")
                parts.append(f"- Action Taken: {scenario.operator_action}")
                parts.append(f"- Outcome: {scenario.outcome_quality}")
                parts.append(f"- Resolution Time: {scenario.time_to_resolution_min} min")
        
        # Request
        parts.append(f"\n## Task")
        parts.append(f"Generate {num_options} DISTINCT options to address this {issue_type} issue.")
        parts.append("Return ONLY a JSON array of options, no other text.")
        
        return "\n".join(parts)
    
    def _validate_options_topology(
        self,
        options: List[GeneratedOption],
        equipment_id: str
    ) -> List[GeneratedOption]:
        """
        Validate options against equipment graph topology (3.2 enhancement).
        
        Ensures affected_nodes and traversal_path reference valid equipment.
        """
        if not self.equipment_graph:
            return options
        
        neighborhood = self.equipment_graph.get_neighborhood(equipment_id, depth=3)
        validated = []
        
        for opt in options:
            # Ensure affected_nodes are valid
            if opt.affected_nodes:
                valid_nodes = [n for n in opt.affected_nodes if n in neighborhood or n in self.equipment_graph._equipment_cache]
                if len(valid_nodes) != len(opt.affected_nodes):
                    invalid = set(opt.affected_nodes) - set(valid_nodes)
                    logger.warning(f"Option {opt.action_type}: removed invalid affected_nodes {invalid}")
                opt.affected_nodes = valid_nodes
            else:
                # Default affected_nodes to equipment_id
                opt.affected_nodes = [equipment_id]
            
            # Ensure traversal_path is valid
            if opt.traversal_path:
                valid_path = [n for n in opt.traversal_path if n in neighborhood or n in self.equipment_graph._equipment_cache]
                opt.traversal_path = valid_path
            else:
                # Default to focus equipment
                opt.traversal_path = [equipment_id]
            
            validated.append(opt)
        
        return validated
    
    async def _call_llm(self, prompt: str) -> List[GeneratedOption]:
        """Call LLM and parse response"""
        if self.llm is None:
            raise ValueError("LLM not available")
        
        # UnifiedLLM uses ask() which is async
        try:
            response = await self.llm.ask(
                messages=[{"role": "user", "content": prompt}],
                system_msgs=[{"role": "system", "content": self.SYSTEM_PROMPT}],
            )
        except Exception as e:
            logger.warning("LLM call failed: %s, using fallback", e)
            raise ValueError(f"LLM call failed: {e}")
        
        # Response is a string content directly
        if isinstance(response, dict):
            content = response.get("content", response.get("text", ""))
        else:
            content = str(response) if response else ""
        
        if not content:
            raise ValueError("Empty LLM response")
        
        # Parse JSON
        # Handle potential markdown code blocks
        if "```json" in content:
            content = content.split("```json")[1].split("```")[0]
        elif "```" in content:
            content = content.split("```")[1].split("```")[0]
        
        try:
            options_data = json.loads(content.strip())
        except json.JSONDecodeError as e:
            logger.error("Failed to parse LLM JSON: %s", e)
            logger.debug("Raw response: %s", content[:500])
            raise
        
        # Convert to GeneratedOption objects
        options = []
        for opt_data in options_data:
            try:
                options.append(GeneratedOption.from_dict(opt_data))
            except Exception as e:
                logger.warning("Failed to parse option: %s", e)
        
        return options
    
    async def _retrieve_scenarios(
        self,
        context: Dict[str, Any],
        issue_type: str
    ) -> List[HistoricalScenario]:
        """Retrieve similar historical scenarios"""
        if not self.scenario_retriever:
            return []
        
        try:
            return await self.scenario_retriever.retrieve_similar(
                context=context,
                issue_type=issue_type,
                k=5
            )
        except Exception as e:
            logger.warning("Scenario retrieval failed: %s", e)
            return []
    
    def _generate_fallback_options(
        self,
        issue_type: str,
        equipment_id: str
    ) -> List[GeneratedOption]:
        """Generate fallback options if LLM fails"""
        # Basic fallback options for common issues
        fallback_templates = {
            "high_head_pressure": [
                GeneratedOption(
                    action_type="reduce_load",
                    action_description=f"Reduce cooling load on {equipment_id} by 15%",
                    equipment_id=equipment_id,
                    risk_score=2,
                    comfort_score=3,
                    energy_impact_pct=-10,
                    mechanism="Reducing load decreases refrigerant pressure",
                ),
                GeneratedOption(
                    action_type="stage_down",
                    action_description=f"Stage down {equipment_id} to partial load",
                    equipment_id=equipment_id,
                    risk_score=2,
                    comfort_score=3,
                    energy_impact_pct=-20,
                    mechanism="Operating at partial load reduces head pressure",
                ),
                GeneratedOption(
                    action_type="investigate",
                    action_description=f"Dispatch technician to inspect {equipment_id}",
                    equipment_id=equipment_id,
                    estimated_time_min=60,
                    risk_score=1,
                    comfort_score=4,
                    mechanism="Investigation may reveal root cause",
                ),
                GeneratedOption(
                    action_type="shutdown",
                    action_description=f"Emergency shutdown of {equipment_id}",
                    equipment_id=equipment_id,
                    risk_score=4,
                    comfort_score=2,
                    requires_shutdown=True,
                    intensity=1.0,
                    mechanism="Prevents potential compressor damage",
                ),
                GeneratedOption(
                    action_type="switch_equipment",
                    action_description=f"Switch to standby unit, take {equipment_id} offline",
                    equipment_id=equipment_id,
                    risk_score=3,
                    comfort_score=4,
                    mechanism="Redundant equipment maintains comfort while issue is addressed",
                ),
            ],
            "default": [
                GeneratedOption(
                    action_type="investigate",
                    action_description=f"Investigate issue on {equipment_id}",
                    equipment_id=equipment_id,
                    risk_score=1,
                    estimated_time_min=60,
                ),
                GeneratedOption(
                    action_type="schedule_maintenance",
                    action_description=f"Schedule maintenance for {equipment_id}",
                    equipment_id=equipment_id,
                    risk_score=1,
                    estimated_time_min=1440,
                ),
                GeneratedOption(
                    action_type="monitor",
                    action_description=f"Continue monitoring {equipment_id}",
                    equipment_id=equipment_id,
                    risk_score=1,
                    intensity=0.1,
                ),
                GeneratedOption(
                    action_type="reduce_load",
                    action_description=f"Reduce load on {equipment_id}",
                    equipment_id=equipment_id,
                    risk_score=2,
                ),
                GeneratedOption(
                    action_type="do_nothing",
                    action_description="No action required at this time",
                    equipment_id=equipment_id,
                    risk_score=1,
                ),
            ],
        }
        
        return fallback_templates.get(issue_type, fallback_templates["default"])
