from fastapi import APIRouter, Depends, HTTPException, BackgroundTasks
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional, Dict, List, Any, AsyncGenerator
import asyncio
import json

from api.dependencies import get_system_state, SystemContainer
from api.security import get_api_key

router = APIRouter(dependencies=[Depends(get_api_key)])

# Models
class ChatRequest(BaseModel):
    message: str
    context: Optional[Dict[str, Any]] = None
    voice_mode: bool = False
    stream: bool = False  # Enable streaming response

class ChatResponse(BaseModel):
    response: str
    tool_calls: List[Dict[str, Any]] = []
    confidence: float = 1.0

class InstructionRequest(BaseModel):
    command: str
    priority: str = "normal"

# Endpoints

@router.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest, sys: SystemContainer = Depends(get_system_state)):
    """Main interaction endpoint for the Agent."""
    if not sys.llm_agent:
        raise HTTPException(status_code=503, detail="Agent Brain not initialized")
    
    # Construct event for the Event Bus
    event = {
        "type": "user_message",
        "payload": {
            "text": req.message,
            "context": req.context or {},
            "source": "api"
        }
    }
    
    try:
        response_generator = sys.llm_agent.handle_streaming(event)
        
        full_text = []
        for token in response_generator:
            full_text.append(token)
            
        return ChatResponse(
            response="".join(full_text),
            tool_calls=[] # We need to capture these from the agent logic
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/chat/stream")
async def chat_stream(req: ChatRequest, sys: SystemContainer = Depends(get_system_state)):
    """
    Streaming chat endpoint using Server-Sent Events (SSE).
    
    Returns tokens as they are generated by the LLM, enabling real-time
    response display in the client.
    """
    if not sys.llm_agent:
        raise HTTPException(status_code=503, detail="Agent Brain not initialized")
    
    async def generate_sse() -> AsyncGenerator[str, None]:
        """Generate SSE events from LLM tokens."""
        event = {
            "type": "user_message",
            "payload": {
                "text": req.message,
                "context": req.context or {},
                "source": "api"
            }
        }
        
        try:
            # Get the response generator
            response_generator = sys.llm_agent.handle_streaming(event)
            
            full_text = []
            for token in response_generator:
                full_text.append(token)
                # Send each token as an SSE event
                yield f"data: {json.dumps({'token': token})}\n\n"
            
            # Send completion event
            yield f"data: {json.dumps({'done': True, 'full_response': ''.join(full_text)})}\n\n"
            
        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
    
    return StreamingResponse(
        generate_sse(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no"
        }
    )

@router.post("/instruct")
async def instruct(req: InstructionRequest, sys: SystemContainer = Depends(get_system_state)):
    """Direct instruction execution."""
    if not sys.tool_executor:
        raise HTTPException(status_code=503, detail="Tool Executor not ready")
        
    # Execute direct command via Tool Executor or LLM planning
    # For now, treat as high-priority chat
    return await chat(ChatRequest(message=f"EXECUTE: {req.command}"), sys)

@router.get("/briefing")
async def get_briefing(sys: SystemContainer = Depends(get_system_state)):
    """Generate daily briefing."""
    # Placeholder for Briefing Generation Logic
    # In V2, call sys.briefing_engine.generate()
    return {
        "summary": "System operating normally. Efficiency at 94%.",
        "alerts": [],
        "suggestions": ["Optimize Chiller Setpoint (+2%)"]
    }

@router.get("/history")
async def get_history(sys: SystemContainer = Depends(get_system_state)):
    """Get Agent interaction history."""
    if sys.state_engine:
        return sys.state_engine.get_history(limit=50)
    return []
